addSbtPlugin("ch.epfl.scala"                     % "sbt-bloop"        % "1.4.0-RC1")
addSbtPlugin("io.github.davidgregory084"         % "sbt-tpolecat"     % "0.1.10")
addSbtPlugin("com.alejandrohdezma"               % "sbt-fix"          % "0.2.6")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.0")
addSbtPlugin("de.heikoseeberger"                 % "sbt-header"       % "5.4.0")
addSbtPlugin("org.scalameta"                     % "sbt-mdoc"         % "2.1.1" )
